### PR TITLE
Utilize SafeJsonResponse().

### PR DESCRIPTION
**Pull request by gomorizsolt**
Issue #122.

### CODE REVIEW

**Comment by gomorizsolt** [comment]
> Which UI glitch do you mean? 🙂

I mean the one that's detailed in #122.

**Comment by gomorizsolt** [comment]
So there's a meaningful error message in place of the star icon.

CleanShot 2020-05-19 at 09 21 54

**Comment by gomorizsolt** [comment]
> This still raises so I don't get how it resolves the issue. Let's talk about it but feel free to merge.

I don't get this. How could you reproduce the issue?

**Comment by gomorizsolt** [comment]
To clarify: without `safeJsonResponse()`, the response coming from the GitHub API is *still* valid even if there's an error since it can be parsed to JSON.

> {message: "Not Found", documentation_url: "https://developer.github.com/v3/repos/#get"}

That's the reason why we could see the "star" icon without any context (title, description and tech icons).

**Comment by gomorizsolt** [comment]
> (and also partially affects #128)

I don't recall this anymore, sorry. I'll take a look into it to what extent `safeJsonResponse()` fixes the error described there.

**Comment by thisismydesign** [comment]
> So there's a meaningful error message in place of the star icon if something goes wrong.

Please don't display anything in this case.

> > This still raises so I don't get how it resolves the issue. Let's talk about it but feel free to merge.
> 
> I don't get this. How could you reproduce the issue?

> To clarify: without safeJsonResponse(), the response coming from the GitHub API is still valid even if there's an error since it can be parsed to JSON.

I meant in the code but this makes sense then, nevermind.

**Pull request merged**
